org: corvumlambda
app: astralis
service: domain-test

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: dev
  region: ca-central-1

plugins:
  - serverless-plugin-typescript
  - serverless-domain-manager

custom:
  customDomain:
    domainName: australis.corvum.io
    basePath: "test"
    stage: ${self:provider.stage}
    createRoute53Record: true

functions: ${file(./functions/functions.yml)}
# ns-158.awsdns-19.com.
# ns-1845.awsdns-38.co.uk.
# ns-1496.awsdns-59.org.
# ns-744.awsdns-29.net.
